export const KEYS = {
  aboutCenter: "aboutCenter",
  mainPage: "mainPage",
  basicInfos: "basicInfos",
  menu: "menu",
  news: "news",
  vacancies: "vacancies",
  vacancy: "vacancy",
  announces: "announces",
  recommends: "recommends",
  photo: "photo",
  video: "video",
  structureOfCenter: "structureOfCenter",
  managers: "managers",
  contacts: "contacts",
  normativeDocs: "normativeDocs",
  veterans: "veterans",
  positionResponsibilities: "positionResponsibilities",
  interRelationPage: "interRelationPage",
  services: "services",
  tradeUnionPage: "tradeUnionPage",
  etiquettesPage: "etiquettesPage",
  departments: "departments",
};
