export const URLS = {
  aboutCenter: "pages/about-center/",
  mainPage: "pages/main-page/",
  basicInfos: "pages/basic-infos/",
  menu: "pages/menus/",
  news: "pages/news/",
  vacancies: "pages/jobs/",
  announces: "pages/announces/",
  recommends: "pages/recommendations/",
  photo: "pages/photos/",
  video: "pages/video/",
  structureOfCenter: "pages/structure-page/",
  managers: "pages/managers/",
  contacts: "pages/contacts/",
  normativeDocs: "pages/normatives-page/",
  veterans: "pages/veterans-page/",
  positionResponsibilities: "pages/position-responsibilities-page/",
  interRelationPage: "pages/inter-relation-page/",
  services: "pages/services/",
  tradeUnionPage: "pages/trade-union-page/",
  etiquettesPage: "pages/etiquettes-page/",
  departments: "pages/departments/",
};
